language: c
compiler:
    - gcc
    - clang
os:
  - linux
  - osx
before_install:
  - sudo pip install cpp-coveralls
script:
    - ./travis_test.sh $TRAVIS_OS_NAME
after_success:
  - coveralls --exclude doc --gcov-options '\-lp'
